# Generated by Django 4.2.14 on 2024-08-02 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_groceryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='shop_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.groceryitem'),
        ),
    ]
