# Generated by Django 4.2.14 on 2024-08-02 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_shoppinglist_temp_shop_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='temp_shop_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lists.groceryitem'),
            preserve_default=False,
        ),
    ]
